/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAppsRouteImport } from './routes/_protected/apps'
import { Route as ProtectedAppsNetworkRouteImport } from './routes/_protected/apps.network'
import { Route as ProtectedAppsNetworkScanRouteImport } from './routes/_protected/apps.network.scan'
import { Route as ProtectedAppsNetworkHistoryRouteImport } from './routes/_protected/apps.network.history'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppsRoute = ProtectedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppsNetworkRoute = ProtectedAppsNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => ProtectedAppsRoute,
} as any)
const ProtectedAppsNetworkScanRoute =
  ProtectedAppsNetworkScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => ProtectedAppsNetworkRoute,
  } as any)
const ProtectedAppsNetworkHistoryRoute =
  ProtectedAppsNetworkHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedAppsNetworkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/apps': typeof ProtectedAppsRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof ProtectedIndexRoute
  '/apps/network': typeof ProtectedAppsNetworkRouteWithChildren
  '/apps/network/history': typeof ProtectedAppsNetworkHistoryRoute
  '/apps/network/scan': typeof ProtectedAppsNetworkScanRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/apps': typeof ProtectedAppsRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof ProtectedIndexRoute
  '/apps/network': typeof ProtectedAppsNetworkRouteWithChildren
  '/apps/network/history': typeof ProtectedAppsNetworkHistoryRoute
  '/apps/network/scan': typeof ProtectedAppsNetworkScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/apps': typeof ProtectedAppsRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/apps/network': typeof ProtectedAppsNetworkRouteWithChildren
  '/_protected/apps/network/history': typeof ProtectedAppsNetworkHistoryRoute
  '/_protected/apps/network/scan': typeof ProtectedAppsNetworkScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/apps'
    | '/dashboard'
    | '/settings'
    | '/'
    | '/apps/network'
    | '/apps/network/history'
    | '/apps/network/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/apps'
    | '/dashboard'
    | '/settings'
    | '/'
    | '/apps/network'
    | '/apps/network/history'
    | '/apps/network/scan'
  id:
    | '__root__'
    | '/_protected'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/apps'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/apps/network'
    | '/_protected/apps/network/history'
    | '/_protected/apps/network/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/apps': {
      id: '/_protected/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof ProtectedAppsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/apps/network': {
      id: '/_protected/apps/network'
      path: '/network'
      fullPath: '/apps/network'
      preLoaderRoute: typeof ProtectedAppsNetworkRouteImport
      parentRoute: typeof ProtectedAppsRoute
    }
    '/_protected/apps/network/scan': {
      id: '/_protected/apps/network/scan'
      path: '/scan'
      fullPath: '/apps/network/scan'
      preLoaderRoute: typeof ProtectedAppsNetworkScanRouteImport
      parentRoute: typeof ProtectedAppsNetworkRoute
    }
    '/_protected/apps/network/history': {
      id: '/_protected/apps/network/history'
      path: '/history'
      fullPath: '/apps/network/history'
      preLoaderRoute: typeof ProtectedAppsNetworkHistoryRouteImport
      parentRoute: typeof ProtectedAppsNetworkRoute
    }
  }
}

interface ProtectedAppsNetworkRouteChildren {
  ProtectedAppsNetworkHistoryRoute: typeof ProtectedAppsNetworkHistoryRoute
  ProtectedAppsNetworkScanRoute: typeof ProtectedAppsNetworkScanRoute
}

const ProtectedAppsNetworkRouteChildren: ProtectedAppsNetworkRouteChildren = {
  ProtectedAppsNetworkHistoryRoute: ProtectedAppsNetworkHistoryRoute,
  ProtectedAppsNetworkScanRoute: ProtectedAppsNetworkScanRoute,
}

const ProtectedAppsNetworkRouteWithChildren =
  ProtectedAppsNetworkRoute._addFileChildren(ProtectedAppsNetworkRouteChildren)

interface ProtectedAppsRouteChildren {
  ProtectedAppsNetworkRoute: typeof ProtectedAppsNetworkRouteWithChildren
}

const ProtectedAppsRouteChildren: ProtectedAppsRouteChildren = {
  ProtectedAppsNetworkRoute: ProtectedAppsNetworkRouteWithChildren,
}

const ProtectedAppsRouteWithChildren = ProtectedAppsRoute._addFileChildren(
  ProtectedAppsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppsRoute: typeof ProtectedAppsRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppsRoute: ProtectedAppsRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
